### ISSUE TITLE
Create manuscript with changes highlighted

### ISSUE THREAD

**Issue by gvwilson** [oicr-gsi/robust-paper#25]
This is encouraged but not required - must be a way to do it for LaTeX under Git.

**Comment by morgantaschuk** [comment]
I made a new LaTeX environment called 'reviewed'.

```
\usepackage{color}

\newenvironment{reviewed}
{ \color{orange} }
```

Now we can use `\begin{reviewed} Text here \end{reviewed}` and it will turn orange. When we submit the final version, we can just remove the text color from the environment.

I think it will be easiest to add the environment tags by diff-ing them against commit f54c8ba59e9f301097a0a5c3db83bfd36e6d102a once the changes are done.

**Comment by morgantaschuk** [comment]
Environment here: 86e2ec9e3fe3af0ae2669faf38699cf5cd370409
