### ISSUE TITLE
A larger nod toward reproducibility

### ISSUE THREAD

**Issue by gvwilson** [oicr-gsi/robust-paper#29]
Reviewer 1 wants more of a nod toward reproducibility.  It's enough of a buzzword these days that we should say something about robustness being a requirement (?) for reproducibility when third-party software is used.

**Comment by morgantaschuk** [comment]
> Reproducibility of software and workflows is increasingly in the
> spotlight. There are passing mentions of reproducibility, and it is
> implicit in many of the guidelines, but it would be good to call it
> out explicitly as a goal beyond making the software robust. For
> example, in the list on p2.
> 
> People like Titus Brown have written a lot about this in blogs. It
> would be useful to reference some of this.

The list in the introduction and the following paragraph have been amended to emphasize the need for reproducibility in scientific computing. I'm not sure if we need to cite something for this. I found a few blogs: 
* Gael Varoquaux. Software for Reproducible Science: Let's not have a misunderstanding. http://gael-varoquaux.info/programming/software-for-reproducible-science-lets-not-have-a-misunderstanding.html
* C. Titus Brown. Replication, reproduction, and remixing in research software. http://ivory.idyll.org/blog/research-software-reuse.html

Ah, what the heck. Let's cite blogs.

In reading these blogs, I notice we also lost the line about "not all software needs to be robust". I have a vague memory of deleting it in a fit of cleaning up. I still think it needs to be said though, so I might resurrect it.

**Comment by morgantaschuk** [comment]
Changes here: 9eec85b547f1c7155afc9cc457a5eb5e9115dfef

Oh nice, it pulls it in according to commit.
