### ISSUE TITLE
Remove mention of inter-institutional collaboration?

### ISSUE THREAD

**Issue by gvwilson** [oicr-gsi/robust-paper#34]
Reviewer 2 questions our mention of this.

**Comment by morgantaschuk** [comment]
> In describing successful software research projects the authors state 
> “...who have adopted strong software engineering approaches, have 
> high standards of reproducibility, use good testing practices, and foster 
> inter-institutional collaborations that grow into strong user bases”.. All 
> of these points can be clearly tied to their rules with the exception of 
> the final statement about inter-institutional collaborations. While such 
> collaborations are desirable, particularly to establish project continuity 
> and longevity, they are not strictly necessary for robustness and this is 
> not further referenced in the manuscript.

That's true. I've changed the line to "and foster strong user bases through constantly evolving, clearly documented, useful, and useable software."
