### ISSUE TITLE
Remove native functions from rule 4

### ISSUE THREAD

**Issue by gvwilson** [oicr-gsi/robust-paper#37]
Reviewer 3: Rule 4 also tends to stuff multiple rules (bolded) into one rule (( limit dependencies, ensure dependencies are available) these 2 are closely related), with “use native functions” which is a very different idea and not what I would expect from a ‘reuse’ rule.

**Comment by morgantaschuk** [comment]
>  Rule 4 also tends to stuff multiple rules (bolded) into one rule 
> (( limit dependencies, ensure dependencies are available) these 
> 2 are closely related), with “ use native functions” which is a very
> different idea and not what I would expect from a ‘reuse’ rule.

I think this is addressed with the changes made for #31
