### ISSUE TITLE
Combine all mentions of documentation

### ISSUE THREAD

**Issue by gvwilson** [oicr-gsi/robust-paper#38]
Reviewer 3: there could have been a single rule (Document your code and usage) that could encompass the points of both Rules 1 and 2 (Readme, usage) as well as the points about documentation from ‘What we left out’.

**Comment by morgantaschuk** [comment]
> Reviewer 1
> I find the relegation of documentation to an additional note rather
> than a rule surprising... If software does not have adequate documentation, it will be
> harder to maintain (either by the original author or by others).
> As mentioned above, documentation is important, and some of the
> existing 10 could be merged to make room for this.

> Reviewer 3
>  Finally the ‘What we left out’ section implicitly defines an additional rule (documentation). In this particular case there could have been a single rule (Document your code and usage) that could encompass the points of both Rules 1 and 2 (Readme, usage) as well as the points from ‘What we left out’.

Combined Rules 1 and 2 with the Documentation section from the end, shortened everything a little, and removed non-documentation paragraphs and placed them elsewhere.
